modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="zombie_ginie_mixtape"
version="1.0.0"
displayName="Zombie ginie mixtape"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="wojmed, MCreator"

[[dependencies.zombie_ginie_mixtape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




